





"""
E:\install\anaconda\envs\huggingface\python.exe E:\project\python\slm_model_train\src\Qwen3_06B\lora_fine_tuning.py
基础模型路径: E:\project\llm\model-data\base-models\Qwen3-0.6B
输出模型路径: E:\project\llm\model-data\train-models\Qwen3-0.6B
==================================================
开始Qwen3-0.6B LoRA微调训练
==================================================
正在加载模型和分词器...
模型和分词器加载完成!
设置LoRA配置...
trainable params: 5,046,272 || all params: 601,096,192 || trainable%: 0.8395
LoRA配置完成!
准备训练数据集...
总训练样本数: 177
Map: 100%|██████████| 177/177 [00:00<00:00, 1165.37 examples/s]
数据集准备完成!
开始训练...
E:\project\python\slm_model_train\src\Qwen3_06B\lora_fine_tuning.py:201: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
 14%|█▍        | 10/69 [10:55<1:11:19, 72.53s/it]{'loss': 5.4448, 'grad_norm': 19.964406967163086, 'learning_rate': 1.8e-05, 'epoch': 0.45}
 29%|██▉       | 20/69 [21:21<47:21, 57.99s/it]{'loss': 3.7822, 'grad_norm': 8.013687133789062, 'learning_rate': 3.8e-05, 'epoch': 0.9}
 43%|████▎     | 30/69 [29:57<36:03, 55.47s/it]{'loss': 2.3764, 'grad_norm': 6.840965747833252, 'learning_rate': 5.8e-05, 'epoch': 1.31}
 58%|█████▊    | 40/69 [39:30<27:50, 57.61s/it]{'loss': 1.654, 'grad_norm': 5.4495744705200195, 'learning_rate': 7.800000000000001e-05, 'epoch': 1.76}
 72%|███████▏  | 50/69 [48:50<18:13, 57.57s/it]{'loss': 1.0789, 'grad_norm': 4.273277759552002, 'learning_rate': 9.8e-05, 'epoch': 2.18}
 87%|████████▋ | 60/69 [59:04<09:11, 61.33s/it]{'loss': 0.7682, 'grad_norm': 5.881645679473877, 'learning_rate': 0.000118, 'epoch': 2.63}
100%|██████████| 69/69 [1:07:25<00:00, 58.63s/it]
{'train_runtime': 4045.3368, 'train_samples_per_second': 0.131, 'train_steps_per_second': 0.017, 'train_loss': 2.271136608676634, 'epoch': 3.0}
训练完成! 模型已保存到: E:\project\llm\model-data\train-models\Qwen3-0.6B
==================================================
训练流程完成!
==================================================

进程已结束，退出代码为 0


"""
"""

for name, _ in model.named_modules():
    print(name)  # 输出所有模块的完整名称


model
model.embed_tokens
model.layers
model.layers.0
model.layers.0.self_attn
model.layers.0.self_attn.q_proj
model.layers.0.self_attn.k_proj
model.layers.0.self_attn.v_proj
model.layers.0.self_attn.o_proj
model.layers.0.self_attn.q_norm
model.layers.0.self_attn.k_norm
model.layers.0.mlp
model.layers.0.mlp.gate_proj
model.layers.0.mlp.up_proj
model.layers.0.mlp.down_proj
model.layers.0.mlp.act_fn
model.layers.0.input_layernorm
model.layers.0.post_attention_layernorm
model.layers.1
model.layers.1.self_attn
model.layers.1.self_attn.q_proj
model.layers.1.self_attn.k_proj
model.layers.1.self_attn.v_proj
model.layers.1.self_attn.o_proj
model.layers.1.self_attn.q_norm
model.layers.1.self_attn.k_norm
model.layers.1.mlp
model.layers.1.mlp.gate_proj
model.layers.1.mlp.up_proj
model.layers.1.mlp.down_proj
model.layers.1.mlp.act_fn
model.layers.1.input_layernorm
model.layers.1.post_attention_layernorm
model.layers.2
model.layers.2.self_attn
model.layers.2.self_attn.q_proj
model.layers.2.self_attn.k_proj
model.layers.2.self_attn.v_proj
model.layers.2.self_attn.o_proj
model.layers.2.self_attn.q_norm
model.layers.2.self_attn.k_norm
model.layers.2.mlp
model.layers.2.mlp.gate_proj
model.layers.2.mlp.up_proj
model.layers.2.mlp.down_proj
model.layers.2.mlp.act_fn
model.layers.2.input_layernorm
model.layers.2.post_attention_layernorm
model.layers.3
model.layers.3.self_attn
model.layers.3.self_attn.q_proj
model.layers.3.self_attn.k_proj
model.layers.3.self_attn.v_proj
model.layers.3.self_attn.o_proj
model.layers.3.self_attn.q_norm
model.layers.3.self_attn.k_norm
model.layers.3.mlp
model.layers.3.mlp.gate_proj
model.layers.3.mlp.up_proj
model.layers.3.mlp.down_proj
model.layers.3.mlp.act_fn
model.layers.3.input_layernorm
model.layers.3.post_attention_layernorm
model.layers.4
model.layers.4.self_attn
model.layers.4.self_attn.q_proj
model.layers.4.self_attn.k_proj
model.layers.4.self_attn.v_proj
model.layers.4.self_attn.o_proj
model.layers.4.self_attn.q_norm
model.layers.4.self_attn.k_norm
model.layers.4.mlp
model.layers.4.mlp.gate_proj
model.layers.4.mlp.up_proj
model.layers.4.mlp.down_proj
model.layers.4.mlp.act_fn
model.layers.4.input_layernorm
model.layers.4.post_attention_layernorm
model.layers.5
model.layers.5.self_attn
model.layers.5.self_attn.q_proj
model.layers.5.self_attn.k_proj
model.layers.5.self_attn.v_proj
model.layers.5.self_attn.o_proj
model.layers.5.self_attn.q_norm
model.layers.5.self_attn.k_norm
model.layers.5.mlp
model.layers.5.mlp.gate_proj
model.layers.5.mlp.up_proj
model.layers.5.mlp.down_proj
model.layers.5.mlp.act_fn
model.layers.5.input_layernorm
model.layers.5.post_attention_layernorm
model.layers.6
model.layers.6.self_attn
model.layers.6.self_attn.q_proj
model.layers.6.self_attn.k_proj
model.layers.6.self_attn.v_proj
model.layers.6.self_attn.o_proj
model.layers.6.self_attn.q_norm
model.layers.6.self_attn.k_norm
model.layers.6.mlp
model.layers.6.mlp.gate_proj
model.layers.6.mlp.up_proj
model.layers.6.mlp.down_proj
model.layers.6.mlp.act_fn
model.layers.6.input_layernorm
model.layers.6.post_attention_layernorm
model.layers.7
model.layers.7.self_attn
model.layers.7.self_attn.q_proj
model.layers.7.self_attn.k_proj
model.layers.7.self_attn.v_proj
model.layers.7.self_attn.o_proj
model.layers.7.self_attn.q_norm
model.layers.7.self_attn.k_norm
model.layers.7.mlp
model.layers.7.mlp.gate_proj
model.layers.7.mlp.up_proj
model.layers.7.mlp.down_proj
model.layers.7.mlp.act_fn
model.layers.7.input_layernorm
model.layers.7.post_attention_layernorm
model.layers.8
model.layers.8.self_attn
model.layers.8.self_attn.q_proj
model.layers.8.self_attn.k_proj
model.layers.8.self_attn.v_proj
model.layers.8.self_attn.o_proj
model.layers.8.self_attn.q_norm
model.layers.8.self_attn.k_norm
model.layers.8.mlp
model.layers.8.mlp.gate_proj
model.layers.8.mlp.up_proj
model.layers.8.mlp.down_proj
model.layers.8.mlp.act_fn
model.layers.8.input_layernorm
model.layers.8.post_attention_layernorm
model.layers.9
model.layers.9.self_attn
model.layers.9.self_attn.q_proj
model.layers.9.self_attn.k_proj
model.layers.9.self_attn.v_proj
model.layers.9.self_attn.o_proj
model.layers.9.self_attn.q_norm
model.layers.9.self_attn.k_norm
model.layers.9.mlp
model.layers.9.mlp.gate_proj
model.layers.9.mlp.up_proj
model.layers.9.mlp.down_proj
model.layers.9.mlp.act_fn
model.layers.9.input_layernorm
model.layers.9.post_attention_layernorm
model.layers.10
model.layers.10.self_attn
model.layers.10.self_attn.q_proj
model.layers.10.self_attn.k_proj
model.layers.10.self_attn.v_proj
model.layers.10.self_attn.o_proj
model.layers.10.self_attn.q_norm
model.layers.10.self_attn.k_norm
model.layers.10.mlp
model.layers.10.mlp.gate_proj
model.layers.10.mlp.up_proj
model.layers.10.mlp.down_proj
model.layers.10.mlp.act_fn
model.layers.10.input_layernorm
model.layers.10.post_attention_layernorm
model.layers.11
model.layers.11.self_attn
model.layers.11.self_attn.q_proj
model.layers.11.self_attn.k_proj
model.layers.11.self_attn.v_proj
model.layers.11.self_attn.o_proj
model.layers.11.self_attn.q_norm
model.layers.11.self_attn.k_norm
model.layers.11.mlp
model.layers.11.mlp.gate_proj
model.layers.11.mlp.up_proj
model.layers.11.mlp.down_proj
model.layers.11.mlp.act_fn
model.layers.11.input_layernorm
model.layers.11.post_attention_layernorm
model.layers.12
model.layers.12.self_attn
model.layers.12.self_attn.q_proj
model.layers.12.self_attn.k_proj
model.layers.12.self_attn.v_proj
model.layers.12.self_attn.o_proj
model.layers.12.self_attn.q_norm
model.layers.12.self_attn.k_norm
model.layers.12.mlp
model.layers.12.mlp.gate_proj
model.layers.12.mlp.up_proj
model.layers.12.mlp.down_proj
model.layers.12.mlp.act_fn
model.layers.12.input_layernorm
model.layers.12.post_attention_layernorm
model.layers.13
model.layers.13.self_attn
model.layers.13.self_attn.q_proj
model.layers.13.self_attn.k_proj
model.layers.13.self_attn.v_proj
model.layers.13.self_attn.o_proj
model.layers.13.self_attn.q_norm
model.layers.13.self_attn.k_norm
model.layers.13.mlp
model.layers.13.mlp.gate_proj
model.layers.13.mlp.up_proj
model.layers.13.mlp.down_proj
model.layers.13.mlp.act_fn
model.layers.13.input_layernorm
model.layers.13.post_attention_layernorm
model.layers.14
model.layers.14.self_attn
model.layers.14.self_attn.q_proj
model.layers.14.self_attn.k_proj
model.layers.14.self_attn.v_proj
model.layers.14.self_attn.o_proj
model.layers.14.self_attn.q_norm
model.layers.14.self_attn.k_norm
model.layers.14.mlp
model.layers.14.mlp.gate_proj
model.layers.14.mlp.up_proj
model.layers.14.mlp.down_proj
model.layers.14.mlp.act_fn
model.layers.14.input_layernorm
model.layers.14.post_attention_layernorm
model.layers.15
model.layers.15.self_attn
model.layers.15.self_attn.q_proj
model.layers.15.self_attn.k_proj
model.layers.15.self_attn.v_proj
model.layers.15.self_attn.o_proj
model.layers.15.self_attn.q_norm
model.layers.15.self_attn.k_norm
model.layers.15.mlp
model.layers.15.mlp.gate_proj
model.layers.15.mlp.up_proj
model.layers.15.mlp.down_proj
model.layers.15.mlp.act_fn
model.layers.15.input_layernorm
model.layers.15.post_attention_layernorm
model.layers.16
model.layers.16.self_attn
model.layers.16.self_attn.q_proj
model.layers.16.self_attn.k_proj
model.layers.16.self_attn.v_proj
model.layers.16.self_attn.o_proj
model.layers.16.self_attn.q_norm
model.layers.16.self_attn.k_norm
model.layers.16.mlp
model.layers.16.mlp.gate_proj
model.layers.16.mlp.up_proj
model.layers.16.mlp.down_proj
model.layers.16.mlp.act_fn
model.layers.16.input_layernorm
model.layers.16.post_attention_layernorm
model.layers.17
model.layers.17.self_attn
model.layers.17.self_attn.q_proj
model.layers.17.self_attn.k_proj
model.layers.17.self_attn.v_proj
model.layers.17.self_attn.o_proj
model.layers.17.self_attn.q_norm
model.layers.17.self_attn.k_norm
model.layers.17.mlp
model.layers.17.mlp.gate_proj
model.layers.17.mlp.up_proj
model.layers.17.mlp.down_proj
model.layers.17.mlp.act_fn
model.layers.17.input_layernorm
model.layers.17.post_attention_layernorm
model.layers.18
model.layers.18.self_attn
model.layers.18.self_attn.q_proj
model.layers.18.self_attn.k_proj
model.layers.18.self_attn.v_proj
model.layers.18.self_attn.o_proj
model.layers.18.self_attn.q_norm
model.layers.18.self_attn.k_norm
model.layers.18.mlp
model.layers.18.mlp.gate_proj
model.layers.18.mlp.up_proj
model.layers.18.mlp.down_proj
model.layers.18.mlp.act_fn
model.layers.18.input_layernorm
model.layers.18.post_attention_layernorm
model.layers.19
model.layers.19.self_attn
model.layers.19.self_attn.q_proj
model.layers.19.self_attn.k_proj
model.layers.19.self_attn.v_proj
model.layers.19.self_attn.o_proj
model.layers.19.self_attn.q_norm
model.layers.19.self_attn.k_norm
model.layers.19.mlp
model.layers.19.mlp.gate_proj
model.layers.19.mlp.up_proj
model.layers.19.mlp.down_proj
model.layers.19.mlp.act_fn
model.layers.19.input_layernorm
model.layers.19.post_attention_layernorm
model.layers.20
model.layers.20.self_attn
model.layers.20.self_attn.q_proj
model.layers.20.self_attn.k_proj
model.layers.20.self_attn.v_proj
model.layers.20.self_attn.o_proj
model.layers.20.self_attn.q_norm
model.layers.20.self_attn.k_norm
model.layers.20.mlp
model.layers.20.mlp.gate_proj
model.layers.20.mlp.up_proj
model.layers.20.mlp.down_proj
model.layers.20.mlp.act_fn
model.layers.20.input_layernorm
model.layers.20.post_attention_layernorm
model.layers.21
model.layers.21.self_attn
model.layers.21.self_attn.q_proj
model.layers.21.self_attn.k_proj
model.layers.21.self_attn.v_proj
model.layers.21.self_attn.o_proj
model.layers.21.self_attn.q_norm
model.layers.21.self_attn.k_norm
model.layers.21.mlp
model.layers.21.mlp.gate_proj
model.layers.21.mlp.up_proj
model.layers.21.mlp.down_proj
model.layers.21.mlp.act_fn
model.layers.21.input_layernorm
model.layers.21.post_attention_layernorm
model.layers.22
model.layers.22.self_attn
model.layers.22.self_attn.q_proj
model.layers.22.self_attn.k_proj
model.layers.22.self_attn.v_proj
model.layers.22.self_attn.o_proj
model.layers.22.self_attn.q_norm
model.layers.22.self_attn.k_norm
model.layers.22.mlp
model.layers.22.mlp.gate_proj
model.layers.22.mlp.up_proj
model.layers.22.mlp.down_proj
model.layers.22.mlp.act_fn
model.layers.22.input_layernorm
model.layers.22.post_attention_layernorm
model.layers.23
model.layers.23.self_attn
model.layers.23.self_attn.q_proj
model.layers.23.self_attn.k_proj
model.layers.23.self_attn.v_proj
model.layers.23.self_attn.o_proj
model.layers.23.self_attn.q_norm
model.layers.23.self_attn.k_norm
model.layers.23.mlp
model.layers.23.mlp.gate_proj
model.layers.23.mlp.up_proj
model.layers.23.mlp.down_proj
model.layers.23.mlp.act_fn
model.layers.23.input_layernorm
model.layers.23.post_attention_layernorm
model.layers.24
model.layers.24.self_attn
model.layers.24.self_attn.q_proj
model.layers.24.self_attn.k_proj
model.layers.24.self_attn.v_proj
model.layers.24.self_attn.o_proj
model.layers.24.self_attn.q_norm
model.layers.24.self_attn.k_norm
model.layers.24.mlp
model.layers.24.mlp.gate_proj
model.layers.24.mlp.up_proj
model.layers.24.mlp.down_proj
model.layers.24.mlp.act_fn
model.layers.24.input_layernorm
model.layers.24.post_attention_layernorm
model.layers.25
model.layers.25.self_attn
model.layers.25.self_attn.q_proj
model.layers.25.self_attn.k_proj
model.layers.25.self_attn.v_proj
model.layers.25.self_attn.o_proj
model.layers.25.self_attn.q_norm
model.layers.25.self_attn.k_norm
model.layers.25.mlp
model.layers.25.mlp.gate_proj
model.layers.25.mlp.up_proj
model.layers.25.mlp.down_proj
model.layers.25.mlp.act_fn
model.layers.25.input_layernorm
model.layers.25.post_attention_layernorm
model.layers.26
model.layers.26.self_attn
model.layers.26.self_attn.q_proj
model.layers.26.self_attn.k_proj
model.layers.26.self_attn.v_proj
model.layers.26.self_attn.o_proj
model.layers.26.self_attn.q_norm
model.layers.26.self_attn.k_norm
model.layers.26.mlp
model.layers.26.mlp.gate_proj
model.layers.26.mlp.up_proj
model.layers.26.mlp.down_proj
model.layers.26.mlp.act_fn
model.layers.26.input_layernorm
model.layers.26.post_attention_layernorm
model.layers.27
model.layers.27.self_attn
model.layers.27.self_attn.q_proj
model.layers.27.self_attn.k_proj
model.layers.27.self_attn.v_proj
model.layers.27.self_attn.o_proj
model.layers.27.self_attn.q_norm
model.layers.27.self_attn.k_norm
model.layers.27.mlp
model.layers.27.mlp.gate_proj
model.layers.27.mlp.up_proj
model.layers.27.mlp.down_proj
model.layers.27.mlp.act_fn
model.layers.27.input_layernorm
model.layers.27.post_attention_layernorm
model.norm
model.rotary_emb
lm_head

"""